[project]
name = "langgraph-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain==1.0.1",
    "langchain-ollama>=1.0.0",
    "langgraph==1.0.1",
]
